<?php

namespace App\Component\Validator\Constraints;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Constraints\DateTimeValidator;
use Symfony\Component\Validator\Exception\UnexpectedTypeException;

class DateTimeMoreNowValidator extends DateTimeValidator
{
 public function validate(mixed $value, Constraint $constraint)
 {
     $valid = parent::validate($value, $constraint); // TODO: Change the autogenerated stub

     }
}