<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('search', TextType::class, [
                'label'=> false,
                'attr'=> ['placeholder'=> 'Recherche un utilisateur'],
                'constraints'=> [new notBlank()],
                'required'=> true,
                'row_attr'=>['class'=> 'mb-0 mx-2']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'method'=> 'GET',
            'csrf_protection'=>false
        ]);
    }

    public function getBlockPrefix(): string
    {
        return ''; // TODO: Change the autogenerated stub
    }
}
